### ISSUE TITLE
Refract your code

### ISSUE THREAD

**Issue by ankitxjoshi** [KaranSharma-gawds/sports-fest#1]
Refract your code and put pycache and database files in gitignore.

**Comment by kayforkaran** [comment]
@MacBox7 please review again now and see if this was resolved.

**Comment by ankitxjoshi** [comment]
The structure is still improper. Why is there a folder called my_routes and a separate file called routes.py. 
If there is a file called controller.py, then perform all db operations like adding user, etc over there and create a function which are then called inside your routes.

**Comment by ankitxjoshi** [comment]
Connection.py and Controller.py perform the same function. Why are you putting a redundant code?

**Comment by kayforkaran** [comment]
routes.py is being replaced by a better structure and until all the previous routes are not replaced, i am planning on keeping it. And thanks for reminding that controller.py. Completely forgot to remove it!
