### ISSUE TITLE
Add authentication to api endpoints

### ISSUE THREAD

**Issue by AnshulMalik** [KaranSharma-gawds/sports-fest#6]
Currently, anyone can upload a file, add results and so on. We must authorize the request and only allow if the user is authorized.

**Comment by kayforkaran** [comment]
@AnshulMalik in every route where the database can be modified, there is an annotation like @login_required which mandates the login of an authorised user which is stored at the time of login. please see the documentation of the same [here](https://flask-login.readthedocs.io/en/latest/).

**Comment by AnshulMalik** [comment]
Okay, then you'll need to do some work sending credentials with ajax calls.
